### ISSUE TITLE
Plugin broke save method using rest-api profile

### ISSUE THREAD

**Issue by erickueen** [grails-plugins/hibernate-logical-delete#3]
**Problem**: When i create an application with the rest-api profile and use the plugin, the http POST method redirects to "index" action instead of "save".

It seems that the plugin overrides the UrlMappings making the API unable to save, even if you change the save method name.

**Expected Behavior**: The http POST method should redirect to the save action in controller.

If I override the plugin source code and compile it with the URL Mappings like a rest-api profile, it works as expected.

The rest-api profile mappings are like this:

```
class UrlMappings {

    static mappings = {
        delete "/$controller/$id(.$format)?"(action:"delete")
        get "/$controller(.$format)?"(action:"index")
        get "/$controller/$id(.$format)?"(action:"show")
        post "/$controller(.$format)?"(action:"guardar")
        put "/$controller/$id(.$format)?"(action:"update")
        patch "/$controller/$id(.$format)?"(action:"patch")

        "/"(controller: 'application', action:'index')
        "500"(view: '/error')
        "404"(view: '/notFound')
    }
}

```

Edit: It also works if I delete the UrlMappings file from the plugin source code.

**Comment by niravassar** [comment]
Thank you. I will look into why this is occurring, and try to replicate it also. In the meantime, can you upload a sample app to github for me. appreciate it

**Comment by erickueen** [comment]
Hi, here's the example app

https://github.com/erickueen/grails-rest-logicald

The **master** branch shows the issue, and the **working_example** branch uses a compiled library without UrlMappings that is working as expected.

**Comment by niravassar** [comment]
i have removed the URLMappings file bc it clashes. thank you

**Comment by mjlachman** [comment]
Could this be included in a release, please? It's breaking my application.
