### ISSUE TITLE
Soft delete + Elasticsearch

### ISSUE THREAD

**Issue by rodolfosaraiva** [grails-plugins/hibernate-logical-delete#6]
There's a way to elasticsearch not index the soft delete data?

Categoria.count() // return 2
Categoria.search("*") // return 3

**Comment by niravassar** [comment]
currently theres is no interception of elasticsearch queries to considered logically deleted data. In elasticSearch can you pass in a where parameter to say deleted=false? that would be a way to filter out the data.
